default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool:     <%= ENV['DATABASE_POOL'] %>
  host:     <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port:     <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: '<%= ENV['DATABASE_DEV_NAME'] %>'

test: &test
  <<: *default
  database:   <%= ENV['DATABASE_TEST_NAME'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_PROD_NAME'] %>
